# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wNNgpfv1Pm6OfjUG1Qbyhgz0kukQHp9T
"""

def kasallik_tashxisi (belgi):
  if belgi== "istima":
   return "Parasetamol iching"
  elif belgi == "bosh og'rig'i ":
   return "Trimol iching"
  elif belgi == "tish og'rig'i":
   return "Quepen iching"
  else:
   return "Shifokorga murojaat qiling"
belgi=input ("Kasallik belgisini kiriting")
natija=kasallik_tashxisi(belgi)
print(natija)

def davlat_poytaxt (belgi):
  if belgi== "O'zbekiston":
   return "Toshkent"
  elif belgi == "Amerika":
   return "Vashington"
  elif belgi == "Fransiya":
   return "Parij"
  else:
   return "Bunday malumot yo'q"
belgi=input ("Qaysi davlat poytaxtini qidiryapsiz?")
natija=davlat_poytaxt(belgi)
print(natija)